# These lines define a route using YAML configuration. The controller used by
# the route (FrameworkBundle:Template:template) is a convenient shortcut when
# the template can be rendered without executing any logic in your own controller.
# See https://symfony.com/doc/current/cookbook/templating/render_without_controller.html
homepage:
    path: /{_locale}
    controller: App\Controller\BlogController::homePage
    requirements:
        _locale: '%app_locales%'
    defaults:
        template: blog/index.html.twig
        _locale: '%locale%'

sitemap:
    path: /sitemap.xml
    controller: App\Controller\SitemapController::sitemap
    requirements:
        _locale: '%app_locales%'
    defaults:
        template: blog/sitemap.xml.twig
        _locale: '%locale%'
        _format: xml
